server:
  port: 8081

spring:
  datasource:
    url: jdbc:clickhouse://127.0.0.1:8123/default
    username: default
    password: example
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.clickhouse.jdbc.ClickHouseDriver

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:mapper/**/*Mapper.xml